language: php

matrix:
  allow_failures:
    - php: hhvm
      env: SYMFONY_VERSION=2.3.*
    - php: hhvm
      env: SYMFONY_VERSION=2.7.*
    - php: hhvm
      env: SYMFONY_VERSION=2.8.*

  include:
    - php: 5.3
      env: SYMFONY_VERSION=2.3.*
    - php: 5.3
      env: SYMFONY_VERSION=2.7.*
    - php: 5.3
      env: SYMFONY_VERSION=2.8.*

    - php: 5.4
      env: SYMFONY_VERSION=2.3.*
    - php: 5.4
      env: SYMFONY_VERSION=2.7.*
    - php: 5.4
      env: SYMFONY_VERSION=2.8.*

    - php: 5.5
      env: SYMFONY_VERSION=2.3.*
    - php: 5.5
      env: SYMFONY_VERSION=2.7.*
    - php: 5.5
      env: SYMFONY_VERSION=2.8.*
    - php: 5.5
      env: SYMFONY_VERSION=3.0.*

    - php: 5.6
      env: SYMFONY_VERSION=2.3.*
    - php: 5.6
      env: SYMFONY_VERSION=2.7.*
    - php: 5.6
      env: SYMFONY_VERSION=2.8.*
    - php: 5.6
      env: SYMFONY_VERSION=3.0.*

    - php: 7.0
      env: SYMFONY_VERSION=2.3.*
    - php: 7.0
      env: SYMFONY_VERSION=2.7.*
    - php: 7.0
      env: SYMFONY_VERSION=2.8.*
    - php: 7.0
      env: SYMFONY_VERSION=3.0.*

env:
  global:
    - SYMFONY_VERSION=""

before_install:
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require --no-update symfony/framework-bundle "$SYMFONY_VERSION"; fi

install:
  - composer install --prefer-source

script:
  - vendor/bin/phpunit
