api:
    resource: "@ApiBundle/Resources/config/routing.yml"
    prefix:   /

model:
    resource: "@ModelBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
