#services:
#    api.example:
#        class: ApiBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

# src/OC/PlatformBundle/Resources/config/services.yml

services:
    api.producer:
            class: ApiBundle\Producer\SafapsProducer
    old_sound_rabbit_mq.upload_profile_producer:
            class:        RabbitMqBundle\RabbitMq\Producer
